### ISSUE TITLE
birds eye review

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamin-usecases#37]
Comments on https://lamin.ai/docs/birds-eye

Generally, I already really like it.

- [x] As you know, I prefer slightly longer introductions, but we generally want to keep them short. However, here I think that we might have to introduce the term "data lineage" in 0.5 sentences. The "why should I care about data lineage" section is so great that I'd actually not make it a drop down here (though I love these in the other sections). I'd also introduce the dataset in 0.5 sentences. I'm confident that with 2-3 sentences we can cover all of this
![image](https://github.com/laminlabs/lamin-usecases/assets/21954664/8f262d46-62fc-409e-8b87-35919b77590e)
- [x] "It’s a mix of a guide & a demo usecase." -> I'd remove this.
- [x] This is pretty long and the "assert you're testuser1" and "login with testuser2" is just noise. Let's try to somehow get rid of this.
![image](https://github.com/laminlabs/lamin-usecases/assets/21954664/f609824e-8090-4d1b-b889-ca057f155013)
Ooooor we are very explicit that we want to simulate multiple users in this notebook to demonstrate collaborative usage
- [x] The new lines seems off here to me
```
# app upload
ln.setup.login("testuser1")
transform = ln.Transform(name="Upload GWS CRISPRa result", type="app")
ln.track(transform)

# upload and analyze the GWS data
filepath = ln.dev.datasets.schmidt22_crispra_gws_IFNG(ln.settings.storage)
file = ln.File(filepath, description="Raw data of schmidt22 crispra GWS")
file.save()
ln.setup.login("testuser2")
transform = ln.Transform(name="GWS CRIPSRa analysis", type="notebook")
ln.track(transform)

file_wgs = ln.File.filter(key="schmidt22-crispra-gws-IFNG.csv").one()
df = file_wgs.load().set_index("id")
hits_df = df[df["pos|fdr"] < 0.01].copy()
file_hits = ln.File(hits_df, description="hits from schmidt22 crispra GWS")
file_hits.save()
```

I'd go for

```
# app upload
ln.setup.login("testuser1")
transform = ln.Transform(name="Upload GWS CRISPRa result", type="app")
ln.track(transform)
filepath = ln.dev.datasets.schmidt22_crispra_gws_IFNG(ln.settings.storage)
file = ln.File(filepath, description="Raw data of schmidt22 crispra GWS")
file.save()

# upload and analyze the GWS data
ln.setup.login("testuser2")
transform = ln.Transform(name="GWS CRIPSRa analysis", type="notebook")
ln.track(transform)
file_wgs = ln.File.filter(key="schmidt22-crispra-gws-IFNG.csv").one()
df = file_wgs.load().set_index("id")
hits_df = df[df["pos|fdr"] < 0.01].copy()
file_hits = ln.File(hits_df, description="hits from schmidt22 crispra GWS")
file_hits.save()
```
- [x] "Let’s see how the data lineage of this looks:" -> Let's see what the data lineage of this looks like
- [x] Add a new line above scanpy & move it 1 line down because it concerns the next section in the hidden code cell
```
screen_hits = file_hits.load()
import scanpy as sc
````
- [ ] Can we show the plot? Would just be fun to look at after there have been so many steps in the data pipeline
![image](https://github.com/laminlabs/lamin-usecases/assets/21954664/ca12be47-d59a-4ae2-bca4-7f259ddc633c)

**Comment by falexwolf** [comment]
One comment on this:
<img width="833" alt="image" src="https://github.com/laminlabs/lamin-usecases/assets/16916678/72f7f9ea-766f-40c0-8d65-8a7b5d68f605">

I'm generally agreed! 0.5 sentences on what data lineage is would be awesome. If everything stays at 2 - 3 sentences, we can also eliminate the dropdown!

One remark: Let's please try to use the same sentences/words/definition that we use in the tutorial.

The idea is that most people will read the readme/landing & tutorial and then come here when they want to know more about data lineage. These people both will have a rough idea of data lineage already and they'll also have seen LaminDB's take on it in the tutorial and on the readme/landing.

A few people might come here without first reading the tutorial. For them the 0.5 sentences on what data lineage is is gold.

But in any case, language should be ultra-consistent between different sections of the docs.

Soonish, I'd also suggest to add both data lineage and provenance to our glossary.

**Comment by falexwolf** [comment]
Really 100% agreed on everything else! @sunnyosun & I are now trying to come up with a video that actually walks through this using LaminDB & LaminApp.

**Comment by falexwolf** [comment]
If you prettify anything, please start with this one!
