### ISSUE TITLE
multi-modal data review

### ISSUE THREAD

**Issue by Zethson** [laminlabs/lamin-usecases#45]
- [x] Has no intro
- [x] We should add a sketch of MuData and link to the Mudata docs. They're not that popular (yet)!
- [x] Why are we hiding where we're getting the data from? Not consistent with other notebooks
- [x] Capitalization -> RNA, ADT
    rna
    adt
- [x] Follow TVR
![image](https://github.com/laminlabs/lamin-usecases/assets/21954664/b7a449f6-e13e-421f-abc7-c9a01eac423f)

**Comment by falexwolf** [comment]
Hey Lukas! Thanks a ton for all these reviews!

100% agreed on everything (also for the other ones).

Ideally, you short-cut the issues and just make PRs to get changes into prod ASAP. :)

**Comment by Zethson** [comment]
@falexwolf yup! Will do

**Comment by falexwolf** [comment]
Thanks, Lukas!
